### ISSUE TITLE
The log does not contain the include parameters

### ISSUE THREAD

**Issue by drbogar** [anton-gogolev/nlog.loki#3]
Hi!

I want to use this NLog Loki target with [my Logfmt Layout], but I can't figure out why the properties and context variables don't appear in the result.
It seems as if the layout does not get these variables. I tried it and it works with console target. What am I doing wrong?

This is my Loki target config:
```
NLog.Loki.LokiTarget lokiTarget = new NLog.Loki.LokiTarget()
{
    BatchSize = 200,
    TaskDelayMilliseconds = 500,
    Endpoint = "http://log.example.com",
    Username = "promtail",
    Password = "SuperSecretPassword",
    OrderWrites = false,
    CompressionLevel = System.IO.Compression.CompressionLevel.NoCompression,
    IncludeCallSite = true,
    IncludeCallSiteStackTrace = true,
    IncludeEventProperties = true,
    IncludeGdc = true,
    IncludeScopeNested = true,
    IncludeScopeProperties = true,
    RetryCount = 5,
    RetryDelayMilliseconds = 500,
    Layout = new NLog.Layouts.LogfmtLayout.LogfmtLayout(),
    Labels = 
    {
        new LokiTargetLabel()
        {
            Name = "host",
            Layout = host
        },
        new LokiTargetLabel()
        {
            Name = "app",
            Layout = assemblyName
        }
    }
};
```

[my Logfmt Layout]: https://github.com/drbogar/NLog.LogfmtLayout

**Comment by snakefoot** [comment]
You have introduced a bug in your layout:

```
    [Layout("LogfmtLayout")]
    [ThreadAgnostic]
    public class LogfmtLayout : Layout
```

For some reason you have decided to add the very special `[ThreadAgnostic]`, which disables capture of context-properties.

**Comment by drbogar** [comment]
Thank you @snakefoot ! This solved the problem.

**Comment by snakefoot** [comment]
The Console-Target is synchronous by default where application-thread is writing, which makes `[ThreadAgnostic]` "work" because context-capture is not needed.

If you wrapped the Console-Target using [AsyncTargetWrapper](https://nlog-project.org/documentation/v5.0.0/html/T_NLog_Targets_Wrappers_AsyncTargetWrapper.htm), then the Layout would also fail (The async background thread cannot render the output, because context-capture has been skipped)
